services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        HOST_UID: ${HOST_UID:-1000}
        HOST_GID: ${HOST_GID:-1000}
    container_name: claude-devvy-container
    hostname: claude-devvy-container
    cap_add:
      - NET_ADMIN # For firewall rules
      - NET_RAW # For iptables
    security_opt:
      - no-new-privileges:true
    ports:
      - "2222:22" # SSH
      - "60000-60010:60000-60010/udp" # Mosh
      - "3000-3010:3000-3010" # Dev servers
    volumes:
      # Projects directory from configuration
      - type: bind
        source: ${PROJECTS_PATH}
        target: /home/devvy/repos
        consistency: delegated # Mac optimization

      # LazyVim config (conditional, read-only)
      - type: bind
        source: ${LAZYVIM_CONFIG_PATH:-${HOME}/.config/nvim}
        target: /home/devvy/.config/nvim
        read_only: true

      # Tmux config (conditional, read-only)
      - type: bind
        source: ${TMUX_CONFIG_PATH:-${HOME}/.config/tmux}
        target: /home/devvy/.config/tmux
        read_only: true

      # Claude config including MCP settings
      - type: bind
        source: ${HOME}/.claude
        target: /home/devvy/.claude
        # read_only: true # These files need to be writable for Claude Code to work

      # VS Code configuration (version controlled)
      - type: bind
        source: ./vscode-config
        target: /home/devvy/vscode-config
        read_only: true

      # Git config (read-only)
      - type: bind
        source: ${GITCONFIG_PATH:-${HOME}/.gitconfig}
        target: /home/devvy/.gitconfig
        read_only: true

      # Authorized keys for SSH access from local machine
      - type: bind
        source: ./secrets
        target: /secrets
        read_only: true
      
      # GitHub SSH keys for authentication
      - type: bind
        source: ./secrets/github
        target: /github-ssh
        read_only: true

      # Persistent data
      - nvim-data:/home/devvy/.local/share/nvim
      - zsh-history:/home/devvy/.local/share/zsh
      - npm-cache:/home/devvy/.npm
      - pnpm-store:/home/devvy/.local/share/pnpm
      - claude-code-data:/home/devvy/.local/share/claude-code
      # VS Code Server persistence (extensions, settings, etc.)
      - vscode-server:/home/devvy/.vscode-server
      - vscode-server-insiders:/home/devvy/.vscode-server-insiders

      # X11 socket for GUI forwarding (macOS)
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      GIT_USER_NAME: ${GIT_USER_NAME}
      GIT_USER_EMAIL: ${GIT_USER_EMAIL}
      LINEAR_API_KEY: ${LINEAR_API_KEY:-}
      INSTALL_LAZYVIM: ${INSTALL_LAZYVIM:-false}
      FIREWALL_ALLOWED_DOMAINS: ${FIREWALL_ALLOWED_DOMAINS:-}
      PLAYWRIGHT_BROWSERS_PATH: /home/devvy/.cache/ms-playwright
      # X11 forwarding for GUI applications
      DISPLAY: host.docker.internal:0
    networks:
      - claude-network
    restart: unless-stopped

networks:
  claude-network:
    driver: bridge

volumes:
  nvim-data:
  zsh-history:
  npm-cache:
  pnpm-store:
  claude-code-data:
  vscode-server:
  vscode-server-insiders:

